<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    10/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/fancieThatCandles/index.php
 */
?>

<br><br>
<h1 class="cursive">
    Code Snippets
</h1>
<p class="products">
</p>

<?php




//$dsn = "mysql:host=".DB_HOST.";dbname=".DB_NAME.";charset=$charset";
//$opt =
//    [
//        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
//        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
//        PDO::ATTR_EMULATE_PREPARES => false,
//    ];
//$dsn = "mysql:host=".DB_HOST.";dbname=".DB_NAME.";charset=$charset";

//$pdo = new PDO($dsn, DB_USER, DB_PASS, $opt);

//new querry

//$qry = 'SELECT * FROM product';
//$stmt = $pdo->query( $qry );
//while ($row = $stmt->fetch())
//{
    //echo '<img src="'.$row['product_image'] . '"/*height="300" width="300"*/><br>';
  //  echo '      <div class="row" style="border: 1px solid black;">';
  //  echo '      <div class="col"><img src="'.$row['product_image'] . '" width="300" height="300"></div>';
  //  echo '      <div class="col" name="prodinfo" style="font-size: 30px">'. $row['product_name']. '</div>';
  //  echo '      <br><input type="submit" style="center content" value="Detail">';
    //echo '      <div class="col" name="prodinfo">'. $row['product_description']. '</div>';
    //echo '      <input type="radio" name="size" value="4oz" checked> 4 oz  ';
    //echo '      <input type="radio" name="size" value="8oz" checked> 8 oz<br>';
    //echo '      Quantity:  <input type="number" name="quantity" min="1" max="10">';
    //echo '      <div class="col" name="prpodinfo">'. '$' . $row['product_price']. '.00 ea.'. '</div>';
    //echo '      <input type="submit" value="order">';
//};
