<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    10/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/fancieThatCandles/index.php
 */
?>
    <br><br>
        <h1 class="cursive">Contact Us</h1>
        <hr>
       <div class="container">
            <form action="index.php" method="post">
                <input type="hidden" name="formtype" value="contact">
                <div class="row">
                    <div class="col-25">
                        <label for="fname"><b>First Name:</b></label>
                    </div>
                    <div class="col-75">
                        <input type="text" id="fname" name="firstname" required="required" placeholder="Your name..">
                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="lname"><b>Last Name:</b></label>
                    </div>
                    <div class="col-75">
                        <input type="text" id="lname" name="lastname" required="required" placeholder="Your last name..">
                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="email"><b>Email:</b></label>
                    </div>
                    <div class="col-75">
                        <input type="text" id="email" name="email" required="required" placeholder="Email Address..">
                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="subject"><b>Reason for contacting us:</b></label>
                    </div>
                    <div class="col-75">
                        <textarea id="subject" name="subject" required="required" placeholder="Please enter the reason for contacting us.." style="height:200px"></textarea>
                    </div>
                </div>
                    <input type="submit" name="submit" value="Submit"><br><br>
       </div>
