<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    10/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/project2/index.php
 */
?>

       <br><br>
        <footer class="lock_footer">
            <small>&copy; Copyright 2018 / Developed By Trevor /
             <a href="includes/contact.phtml">Contact Us</a></small>
        </footer>
    </body>
</html>
