<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    10/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/fancieThatCandles/index.php
 */
?>

<br><br>
<h1 class="cursive" >Developed By Trevor</h1>
 <p class="about" >
     This site will serve as my resume, once you create a log in you'll be grated access to<br>
     code snippets from multiple languages to demonstrate some of my knowledge. Please ubderstand<br>
     you will not have complete working programs. More examples can be sent to potential employers,<br>
     all requests can be made through the contact form.
 </p>


</html>

