<?php
/**
 * Trevor Kamin
 * CIS 222 Project 1
 *
 * This website was used as my PHP w/ MYSQL course with professor Banks. It will
 *be used in a production for Fancie That Candles. This is a complete online
 * store, and will be fully functional when completed.
 *
 * PHP version 5.4.45
 *
 * @package    Fancie That Candles
 * @author     Trevor Kamin
 * @copyright  2018 Fancie That Candles
 * @version    10/09/2018
 * @link       https://cislinux.hfcc.edu/~tkamin/fancieThatCandles/index.php
 */
?>

<!-- Load an icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="navbar">
    <a href="index.php?page=home"><i class="fa fa-fw fa-home"></i> Home</a>
    <a href="index.php?page=code"><i class="fa fa-fw fa-fire"></i> Code</a>
    <a href="index.php?page=contact"><i class="fa fa-fw fa-envelope"></i> Contact</a>
    <a href="index.php?page=login"><i class="fa fa-fw fa-user"></i> Login</a>
</div>
